export const initialEdges = [
  { id: 'e1-2', source: '1', target: '2', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  { id: 'e1-5', source: '1', target: '5', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  { id: 'e1-8', source: '1', target: '8', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  {
    id: 'e1-11',
    source: '1',
    target: '11',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e1-15',
    source: '1',
    target: '15',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e1-18',
    source: '1',
    target: '18',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  { id: 'e2-3', source: '2', target: '3', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  { id: 'e2-4', source: '2', target: '4', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  { id: 'e5-6', source: '5', target: '6', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  { id: 'e5-7', source: '5', target: '7', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  { id: 'e8-9', source: '8', target: '9', type: 'smoothstep', markerEnd: { type: 'arrowclosed' } },
  {
    id: 'e8-10',
    source: '8',
    target: '10',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e11-12',
    source: '11',
    target: '12',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e11-13',
    source: '11',
    target: '13',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e13-14',
    source: '13',
    target: '14',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e15-16',
    source: '15',
    target: '16',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e15-17',
    source: '15',
    target: '17',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e18-19',
    source: '18',
    target: '19',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
  {
    id: 'e18-20',
    source: '18',
    target: '20',
    type: 'smoothstep',
    markerEnd: { type: 'arrowclosed' },
  },
];
